// <auto-generated />
using System;
using MainApp;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MainApp.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20221211103123_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.11");

            modelBuilder.Entity("InventoryLibrary.Entity.Agent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Agents");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Login = "Test",
                            Password = "Test"
                        });
                });

            modelBuilder.Entity("InventoryLibrary.Entity.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AgentId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("TEXT");

                    b.Property<int>("WareHouseId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AgentId");

                    b.HasIndex("WareHouseId");

                    b.ToTable("Items");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AgentId = 1,
                            Name = "Люстра",
                            TimeStamp = new DateTime(2022, 12, 11, 13, 31, 22, 902, DateTimeKind.Local).AddTicks(2676),
                            WareHouseId = 1
                        },
                        new
                        {
                            Id = 2,
                            AgentId = 1,
                            Name = "Ковер",
                            TimeStamp = new DateTime(2022, 12, 11, 13, 31, 22, 902, DateTimeKind.Local).AddTicks(2686),
                            WareHouseId = 1
                        },
                        new
                        {
                            Id = 3,
                            AgentId = 1,
                            Name = "Холодильник",
                            TimeStamp = new DateTime(2022, 12, 11, 13, 31, 22, 902, DateTimeKind.Local).AddTicks(2687),
                            WareHouseId = 2
                        },
                        new
                        {
                            Id = 4,
                            AgentId = 1,
                            Name = "Дверь",
                            TimeStamp = new DateTime(2022, 12, 11, 13, 31, 22, 902, DateTimeKind.Local).AddTicks(2688),
                            WareHouseId = 2
                        });
                });

            modelBuilder.Entity("InventoryLibrary.Entity.WareHouse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("WareHouses");

                    b.HasData(
                        new
                        {
                            Id = 1
                        },
                        new
                        {
                            Id = 2
                        });
                });

            modelBuilder.Entity("InventoryLibrary.Entity.Item", b =>
                {
                    b.HasOne("InventoryLibrary.Entity.Agent", "Agent")
                        .WithMany("Items")
                        .HasForeignKey("AgentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InventoryLibrary.Entity.WareHouse", "WareHouse")
                        .WithMany("Items")
                        .HasForeignKey("WareHouseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Agent");

                    b.Navigation("WareHouse");
                });

            modelBuilder.Entity("InventoryLibrary.Entity.Agent", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("InventoryLibrary.Entity.WareHouse", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
